enum InjectableModules {
    CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY',
    LINKS_REPOSITORY = 'LINKS_REPOSITORY',
    LINK_SHORTENER_PROVIDER = 'LINK_SHORTENER_PROVIDER',
    MATRIX_CODERENDER_PROVIDER = 'MATRIX_CODERENDER_PROVIDER',
}

export { InjectableModules };
